# staging overrides; image tags are written by .github/workflows/cd.yml, never by hand.
domain: rescope-staging.example.com

images:
  api:
    tag: ""
  scraper:
    tag: ""
  web:
    tag: ""

backup:
  # terraform output backups_bucket
  bucket: ""
